on:
  push:
    branches:
      - development

permissions:
  contents: write
  pull-requests: write

name: release-dev

jobs:
  release-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          skip-github-release: true
          command: release-pr
